//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptekApp0215.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settng
    {
        public int ID { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Header { get; set; }
    }
}
